---
- name: Manage Windows
  hosts: win
  become: false
  gather_facts: false
  tasks:
  - name: Join AD
    win_shell: |
      netdom.exe join $env:computername /domain:pacificovida.com /UserD:pacificovida.com\administrator /ou:OU=Recursos TI\Servidores\WSUS\Windows2016,DC=pacificovida,DC=com /PasswordD:Jerico.4878
    register: task_result
    ignore_errors: yes
  - name: Reboot immediately if there was a change.
    win_shell: |
      Start-Sleep -Seconds 5
      Restart-Computer
    when: task_result is changed
  - name: Wait for the reboot to complete if there was a change.
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
    when: task_result is changed  
  
